ARG USER=node
ARG WORK_DIR=/usr/local/app
ARG INIT_PATH=/usr/local/bin/dumb-init
ARG INIT_URL=https://github.com/Yelp/dumb-init/releases/download/v1.2.5/dumb-init_1.2.5_x86_64

FROM node:20-alpine AS dev

ARG USER
ARG WORK_DIR
ARG INIT_PATH
ARG INIT_URL

ENV TZ=America/Sao_Paulo NODE_ENV=development LANG=C.UTF-8

RUN set -euxo pipefail;\
  apk update;\
  apk add --no-cache tzdata nano ca-certificates git curl;\
  curl --fail --silent --show-error --location ${INIT_URL} --output ${INIT_PATH};\
  chmod +x ${INIT_PATH};

WORKDIR ${WORK_DIR}

COPY --chown=${USER}:${USER} package.json package-lock.json ${WORK_DIR}/

RUN [ "npm", "install" ]

COPY --chown=${USER}:${USER} . ${WORK_DIR}

USER ${USER}

EXPOSE 3000 9229

ENTRYPOINT [ "/usr/local/bin/dumb-init", "--" ]

CMD [ "npm", "run", "dev" ]
