services:
  scylla-1:
    image: scylladb/scylla:6.2
    container_name: scylla-1
    command:
      - --smp=2
      - --memory=2GB
      - --overprovisioned=1
      - --developer-mode=1
      - --seeds=scylla-1
    ports:
      - '9042:9042'
      - '19042:19042'
    expose:
      - '19042'
    networks:
      - app-network
    healthcheck:
      test:
        - CMD-SHELL
        - cqlsh -e "SHOW VERSION" || exit 1
      interval: 15s
      timeout: 30s
      retries: 15
      start_period: 30s
networks:
  app-network:
    name: app-network
    driver: bridge
