version: '3.8'

services:
  scylla-js-driver-test:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: scylla-js-driver-test
    image: scylla-js-driver-test:dev
    hostname: scylla-js-driver-test
    tty: true
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-256color
    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules
    ports:
      - 5000:9229
      - 3000:3000
    networks:
      - scylla-js-driver-test
networks:
  scylla-js-driver-test:
    name: scylla-js-driver-test
    driver: bridge
