version: '3.8'

services:
  ts-node-archref:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ts-node-archref
    image: ts-node-archref:dev
    hostname: ts-node-archref
    tty: true
    environment:
      - COLORTERM=truecolor
      - TERM=xterm-256color
    volumes:
      - .:/usr/local/app
      - /usr/local/app/node_modules
    ports:
      - 5000:9229
      - 3000:3000
    networks:
      - ts-node-archref
networks:
  ts-node-archref:
    name: ts-node-archref
    driver: bridge
